INSERT INTO BSE (pid, progname, course_code, course_name, sem_offered, prereq, status)
VALUES ('PBSE', 'Bachelor of Software Engineering', 'CS111', 'Introduction to C++', 'One','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'MA111', 'Linear Algebra', 'One','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'ST131', 'Statistics', 'One','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'UU114', 'Academic English', 'One/Two','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'MA161', 'Discrete Mathematics', 'Two','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'MG101', 'Management for Developers', 'Two','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS140', 'Software Engineering Fundamentals', 'Two','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'UU100A', 'ICT Tools', 'One/Two','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS112', 'Data Structures', 'Two','CS111', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS211', 'Computer Organization', 'One','CS111', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS214', 'Algorithms', 'Two','CS112', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS218', 'Networks', 'One','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS230', 'Software', 'Two','CS140', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS241', 'Building Applications', 'Two','CS112', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'IS221', 'Web Development', 'One','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'IS222', 'Database Management', 'One','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'UU200', 'Ethics', 'One/Two','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS001', 'Foundations of Professionalism', 'One/Two','Year 2, Semester One', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS310', 'Routing Protcols', 'One','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS311', 'Distributed Computing', 'One','CS211', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS324', 'Architectures and Computing', 'Two','CS214', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'IS333', 'Project Management', 'One','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS341', 'Testing and Maintenance', 'Two','CS241', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'IS314', 'Project', 'Two','200 Level Units', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'IS328', 'Data Mining', 'Two','None', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS415', 'Advanced Software Engineering', 'One','300 Level Units', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS424', 'Big Data', 'One','IS328', 'Available'),
('PBSE', 'Bachelor of Software Engineering', 'CS400', 'IEP', 'Two','All Previous Units', 'Available');