INSERT INTO BNS (pid, progname, course_code, course_name, sem_offered, prereq, status)
VALUES ('PBNS', 'Bachelor of Networks and Security', 'CS111', 'Introduction to C++', 'One','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'MA111', 'Linear Algebra', 'One','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'ST131', 'Statistics', 'One','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'UU114', 'Academic English', 'One/Two','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'MA161', 'Discrete Mathematics', 'Two','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'MG101', 'Management for Developers', 'Two','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS150', 'Networks and Security Fundamentals', 'Two','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'UU100A', 'ICT Tools', 'One/Two','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS112', 'Data Structures', 'Two','CS111', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS211', 'Computer Organization', 'One','CS111', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS214', 'Algorithms', 'Two','CS112', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS218', 'Networks', 'One','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS215', 'Building Applications', 'Two','CS112', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'IS221', 'Web Development', 'One','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'IS222', 'Database Management', 'One','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'UU200', 'Ethics', 'One/Two','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS001', 'Foundations of Professionalism', 'One/Two','Year 2, Semester One', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS310', 'Routing Protcols', 'One','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS311', 'Distributed Computing', 'One','CS211', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS317', 'Security', 'One','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS324', 'Architectures and Computing', 'Two','CS214', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'IS333', 'Project Management', 'One','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS350', 'Distributed Computing', 'One','CS215', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS351', 'Testing and Maintenance', 'One','CS218', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS352', 'Project', 'Two','CS351', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'IS328', 'Data Mining', 'Two','None', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS415', 'Advanced Networks and Security', 'One','300 Level Units', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CS424', 'Big Data', 'One','IS328', 'Available'),
('PBNS', 'Bachelor of Networks and Security', 'CSS400', 'IEP', 'Two','All Previous Units', 'Available');